/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./templates/**/*.html",
    "./static/**/*.js",
  ],
  theme: {
    extend: {
      colors: {
        paper: {
          DEFAULT: '#f5f6f9',
          2: '#ecedf2',
          3: '#e4e6ed',
        },
        ink: {
          DEFAULT: '#272a33',
          2: '#5c6170',
          muted: '#7a7f8e',
        },
        accent: {
          DEFAULT: '#1f3a64',
          2: '#2d4f82',
          light: '#e8edf5',
        },
        rule: '#d3d6e0',
      },
      fontFamily: {
        display: ['"DM Serif Display"', 'Georgia', 'serif'],
        body: ['"Geist"', 'system-ui', 'sans-serif'],
        mono: ['"Geist Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'display': ['clamp(1.75rem, 4vw, 2.25rem)', { lineHeight: '1.15', fontWeight: '400' }],
      },
      borderRadius: {
        'card': '1rem',
      },
    },
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [{
      dishub: {
        "primary": "#1f3a64",
        "primary-content": "#ffffff",
        "secondary": "#2d4f82",
        "secondary-content": "#ffffff",
        "accent": "#1f3a64",
        "accent-content": "#ffffff",
        "neutral": "#3d4852",
        "neutral-content": "#e4e8ee",
        "base-100": "#e4e8ee",
        "base-200": "#d5dae2",
        "base-300": "#c9cfd9",
        "base-content": "#3d4852",
        "info": "#2d4f82",
        "info-content": "#ffffff",
        "success": "#16a34a",
        "success-content": "#ffffff",
        "warning": "#d97706",
        "warning-content": "#ffffff",
        "error": "#dc2626",
        "error-content": "#ffffff",
        "--rounded-box": "1.125rem",
        "--rounded-btn": "0.875rem",
        "--rounded-badge": "9999px",
        "--animation-btn": "0s",
        "--animation-input": "0s",
        "--btn-focus-scale": "1",
      },
      "dishub-dark": {
        "primary": "#7a9ccb",
        "primary-content": "#0d1420",
        "secondary": "#5f86bd",
        "secondary-content": "#0d1420",
        "accent": "#7a9ccb",
        "accent-content": "#0d1420",
        "neutral": "#aeb6c4",
        "neutral-content": "#1c2129",
        "base-100": "#1c2129",
        "base-200": "#232933",
        "base-300": "#2c333f",
        "base-content": "#c8cdd8",
        "info": "#5f86bd",
        "info-content": "#0d1420",
        "success": "#34d399",
        "success-content": "#052e16",
        "warning": "#fbbf24",
        "warning-content": "#422006",
        "error": "#f87171",
        "error-content": "#450a0a",
        "--rounded-box": "1.125rem",
        "--rounded-btn": "0.875rem",
        "--rounded-badge": "9999px",
        "--animation-btn": "0s",
        "--animation-input": "0s",
        "--btn-focus-scale": "1",
      }
    }],
    darkTheme: "dishub-dark",
    logs: false,
  },
}
